select p.PERMITNUMBER, 
p.APDTTM,
p.PERMITISSUEDATE,
p.PERMITTYPE,
p.TYPEOFWORK
from imsv7.li_allpermits p
where TO_DATE(p.APDTTM, 'YYYY-MM-DD') = TO_DATE(p.PERMITISSUEDATE, 'YYYY-MM-DD')
and p.APDTTM >= '01-JAN-2016'